# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=128)),
                ('addr', models.CharField(max_length=128)),
                ('from_field', models.CharField(db_column='from', max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('rssi', models.IntegerField()),
                ('ssid', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.IntegerField()),
                ('time', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.CharField(max_length=128, unique=True)),
                ('label', models.CharField(max_length=128)),
            ],
        ),
    ]
